const BANDS = [
  "Amadou and Mariam",
  "The Andrews Sisters",
  "The Animals",
  "Arcade Fire",
  "Black Flag",
  "Black Sabbath",
  "Blondie",
  "Booker T. and the MG’s",
  "The Boswell Sisters",
  "The Allman Brothers Band",
  "Boston",
  "Boyz II Men",
  "Brooks & Dunn",
  "Buffalo Springfield",
  "The Byrds",
  "Calle 13",
  "My Chemical Romance",
  "The Chemical Brothers",
  "Chicago",
  "The Clash",
  "The Coasters",
  "Coldplay",
  "The Four Tops",
  "Fugazi",
  "The Gang of Four",
  "Grandmaster Flash and the Furious Five",
  "The Grateful Dead",
  "Green Day",
  "Cream",
  "Creedence Clearwater Revival",
  "The Decemberists",
  "Earth, Wind & Fire",
  "Emerson Lake & Palmer",
  "The Everly Brothers",
  "Death Cab for Cutie",
  "Genesis",
  "The Kinks",
  "Gladys Knight and the Pips",
  "Kool and the Gang",
  "Kraftwerk",
  "Ladysmith Black Mambazo",
  "Love",
  "The Beach Boys",
  "The Beastie Boys",
  "The Beatles",
  "The Bee Gees",
  "Big Star",
  "The Lovin’ Spoonful",
  "Frankie Lymon and the Teenagers",
  "The Flamingos",
  "Def Leppard",
  "Lynyrd Skynyrd",
  "The MC5",
  "The Mills Brothers",
  "The Mamas and the Papas",
  "The Mekons",
  "Metallica",
  "Modest Mouse",
  "De La Soul",
  "The New York Dolls",
  "New Order",
  "Devo",
  "Guns N’ Roses",
  "Led Zeppelin",
  "Little Anthony and the Imperials",
  "The Louvin Brothers",
  "The Band",
  "The Monkees",
  "The Moody Blues",
  "The Moonglows",
  "Mumford & Sons",
  "Fleetwood Mac",
  "The Eagles",
  "The Flying Burrito Brothers",
  "The Four Seasons",
  "The Ink Spots",
  "The Isley Brothers",
  "The Jam",
  "The Jefferson Airplane",
  "The Jesus and Mary Chain",
  "Jonas Brothers",
  "Joy Division",
  "The Judds",
  "The Kingston Trio",
  "Crosby, Stills & Nash",
  "Daft Punk",
  "Hüsker Dü",
  "The Hollies",
  "Iggy and the Stooges",
  "The Dillards",
  "Dion and the Belmonts",
  "Dire Straits",
  "Dixie Chicks",
  "The Doors",
  "The Drifters",
  "Nine Inch Nails",
  "Nirvana",
  "The Pet Shop Boys",
  "Peter, Paul and Mary",
  "Pink Floyd",
  "Pixies",
  "The Platters",
  "Poco",
  "The Police",
  "Portishead",
  "OutKast",
  "Parliament-Funkadelic",
  "Pavement",
  "The O’Jays",
  "The Ohio Players",
  "Pearl Jam",
  "Pere Ubu",
  "R.E.M.",
  "Talking Heads",
  "Rage Against the Machine",
  "The Ramones",
  "Rascal Flatts",
  "TV on the Radio",
  "Sam and Dave",
  "Public Enemy",
  "Puffy AmiYumi",
  "Red Hot Chili Peppers",
  "The Replacements",
  "The Rolling Stones",
  "Spice Girls",
  "Television",
  "The Temptations",
  "Tinariwen",
  "The Yardbirds",
  "Yes",
  "Yo La Tengo",
  "ZZ Top",
  "Roxy Music",
  "Run-D.M.C.",
  "Radiohead",
  "Stanley Brothers",
  "The Staple Singers",
  "Santana",
  "The Sex Pistols",
  "The Shadows",
  "The Soul Stirrers",
  "The Shirelles",
  "Sleater-Kinney",
  "Sly and the Family Stone",
  "Smashing Pumpkins",
  "Toots and the Maytals",
  "Traffic",
  "The White Stripes",
  "The Turtles",
  "U2",
  "Van Halen",
  "The Velvet Underground",
  "The Ventures",
  "The Weavers",
  "The Who",
  "Steely Dan",
  "The Strokes",
  "Queen",
  "One Direction",
  "The Orioles",
  "Wilco",
  "The Smiths",
  "X",
  "Sonic Youth",
];

export { BANDS };
